### ISSUE TITLE
Problems with grunt build

### ISSUE THREAD

**Issue by brunoshow** [beeman/loopback-angular-admin#102]
Im trying run your project locally but im heaving some problems on `grunt build`.

*Failed at the loopback-angular-admin@0.1.1 postinstall script 'bower install && grunt build
### npm.log:
```
283 info install loopback-angular-admin@0.1.1
284 info postinstall loopback-angular-admin@0.1.1
285 verbose unsafe-perm in lifecycle true
286 info loopback-angular-admin@0.1.1 Failed to exec postinstall script
287 verbose stack Error: loopback-angular-admin@0.1.1 postinstall: `bower install && grunt build`
287 verbose stack Exit status 6
287 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
287 verbose stack     at EventEmitter.emit (events.js:110:17)
287 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
287 verbose stack     at ChildProcess.emit (events.js:110:17)
287 verbose stack     at maybeClose (child_process.js:1015:16)
287 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
288 verbose pkgid loopback-angular-admin@0.1.1
289 verbose cwd /Users/brunorosa/Documents/TCC/loopback/api-admin-test-heroku/admin-fa-test
290 error Darwin 14.4.0
291 error argv "node" "/usr/local/bin/npm" "i"
292 error node v0.12.2
293 error npm  v2.13.2
294 error code ELIFECYCLE
295 error loopback-angular-admin@0.1.1 postinstall: `bower install && grunt build`
295 error Exit status 6
296 error Failed at the loopback-angular-admin@0.1.1 postinstall script 'bower install && grunt build'.
296 error This is most likely a problem with the loopback-angular-admin package,
296 error not with npm itself.
296 error Tell the author that this fails on your system:
296 error     bower install && grunt build
296 error You can get their info via:
296 error     npm owner ls loopback-angular-admin
296 error There is likely additional logging output above.
297 verbose exit [ 1, true ]
```

**Comment by beeman** [comment]
Hi @brunoshow , do you have `bower` and `grunt-cli` installed globally?

    $ npm install -g bower grunt-cli
