### ISSUE TITLE
Unhandled rejection Error: Your Node runtime does support ES6 Promises. 

### ISSUE THREAD

**Issue by Airdigit** [beeman/loopback-angular-admin#159]
Hello please help with this i am getting the fallowing error , when run grunt serve on ubuntu machine 

Unhandled rejection Error: Your Node runtime does support ES6 Promises. Set "global.Promise" to your preferred implementation of promises.
    at Object.throwPromiseNotDefined (/home/ubuntu/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/utils.js:486:9)
    at getThen (/home/ubuntu/loopback-angular-admin/node_modules/bluebird/js/main/thenables.js:37:15)
    at tryCatcher (/home/ubuntu/loopback-angular-admin/node_modules/bluebird/js/main/util.js:26:23)
    at tryConvertToPromise (/home/ubuntu/loopback-angular-admin/node_modules/bluebird/js/main/thenables.js:23:42)
    at PromiseArray.init [as _init] (/home/ubuntu/loopback-angular-admin/node_modules/bluebird/js/main/promise_array.js:79:28)
    at new PromiseArray (/home/ubuntu/loopback-angular-admin/node_modules/bluebird/js/main/promise_array.js:24:10)
    at Function.Promise.all (/home/ubuntu/loopback-angular-admin/node_modules/bluebird/js/main/promise.js:173:12)
    at Object.module.exports [as func] (/home/ubuntu/loopback-angular-admin/server/boot/99-fake-data.js:40:11)
    at /home/ubuntu/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:253:9
    at iterate (/home/ubuntu/loopback-angular-admin/node_modules/async/lib/async.js:149:13)
    at /home/ubuntu/loopback-angular-admin/node_modules/async/lib/async.js:160:25
    at /home/ubuntu/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:255:7
    at iterate (/home/ubuntu/loopback-angular-admin/node_modules/async/lib/async.js:149:13)
    at /home/ubuntu/loopback-angular-admin/node_modules/async/lib/async.js:160:25
    at /home/ubuntu/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:255:7
    at iterate (/home/ubuntu/loopback-angular-admin/node_modules/async/lib/async.js:149:13)

**Comment by beeman** [comment]
Hey @Airdigit , can you give some information about which version of node, npm and ubuntu you are using?
