### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by PhilippeCorreges** [beeman/loopback-angular-admin#174]
Hi,
I have the same issue with node 5.10 and node 5.5. 
I git clone the repo and run a npm install on my package.json and then start server.js.
The explorer is showing and working!

Nevertheless I am getting those errors in the console:/usr/local/bin/node server.js
Configuring passport
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:252:17)
    at DataSource.once (events.js:278:8)
    at DataSource.ready (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/datasource.js:2110:8)
    at stillConnecting (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/dao.js:367:23)
    at Function.DataAccessObject.create (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/dao.js:160:27)
    at Object.module.exports [as func](/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/server/boot/passport.js:78:22)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:294:9
    at iterate (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:146:13)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:157:25
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:146:13)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:157:25
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:146:13)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:157:25
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:296:7
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:252:17)
    at DataSource.once (events.js:278:8)
    at DataSource.ready (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/datasource.js:2111:8)
    at stillConnecting (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/dao.js:367:23)
    at Function.DataAccessObject.create (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-datasource-juggler/lib/dao.js:160:27)
    at Object.module.exports [as func](/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/server/boot/passport.js:78:22)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:294:9
    at iterate (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:146:13)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:157:25
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:146:13)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:157:25
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:146:13)
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/async/lib/async.js:157:25
    at /Users/IOSoftwareSAS/WebstormProjects/loopback-angular-admin/node_modules/loopback-boot/lib/executor.js:296:7
Web server listening at: http://localhost:3000
Creating default settings
Browse your REST API at http://localhost:3000/explorer

Any idea ?

Kind Regards,

Philippe

**Comment by beeman** [comment]
Hi @PhilippeCorreges , can you give some information/specs about the machine where your are running it on?

**Comment by PhilippeCorreges** [comment]
Hi beeman
this is a mac : 
OS El Capitan
8Go Memory
2,7 GHz Intel Core i5

**Comment by PhilippeCorreges** [comment]
I have just tested it on another machine : Same error : /usr/local/bin/node server.js
Configuring passport
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:239:17)
    at DataSource.once (events.js:265:8)

**Comment by PhilippeCorreges** [comment]
This has something to do with passport.js in boot folder.
I tried with another providers.json (Working on another app with correct links ....) and the problem is the same.
In passport.js the code had the problem with: 

AuthProvider.create(entry, function(err, data) {
          if (err) {
            console.log(err);
          }
        });

That is why I went to see where the problem comes from. Now, I cut almost all providers.json file to let only : 
{
  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "username",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/",
    "failureRedirect": "/local",
    "failureFlash": true
  }
}

The app is starting correctly with an error : /usr/local/bin/node server.js
Configuring passport
Creating default settings
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Error: Cannot GET /
    at raiseUrlNotFoundError

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
