### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by Necter** [beeman/loopback-angular-admin#181]
Hello,

Thank-you for providing this starter project. It installed without any problems. I'm able to bring up the app, however. I receive the error "Cannot read property 'then' of undefined." I'm on a Windows 7 machine. Any insight into what I can do to fix this issue would be greatly appreciated.

![image](https://cloud.githubusercontent.com/assets/6878744/15236485/f367b570-1892-11e6-8836-36d86ac73d83.png)

**Comment by beeman** [comment]
Hi @Necter , thanks for your interest in this project.

I'm not sure what is going wrong here, but what I do notice are the error messages down in the console, it looks like the app is trying to connect to `http://localhost`, without a port.

Can you shed some light on how you are running and starting the project? Do you get any error messages in the command line?

**Comment by Necter** [comment]
Regarding the missing host: Apologies, I accidentally deleted the port number in the instance that I ran for that screenshot. I've since fixed it and get a similar error in the Chrome:

![image](https://cloud.githubusercontent.com/assets/6878744/15270666/7379bdae-19f5-11e6-8bac-e8591196e1f6.png)

No, there are no errors in the command window/console:

![image](https://cloud.githubusercontent.com/assets/6878744/15270668/8d488c1a-19f5-11e6-9d17-eb066ef45df4.png)

Here is what I've done so far:

On a Windows 7 machine, I created a directory and ran the one-liner install. (Node/npm, grunt, and bower had already been installed globally.)

I edited the grunt.js file and made the following changes to the appConfig variable so that it now looks like: 

  var appConfig = {
    app: require('./bower.json').appPath || 'client/app',
    test: require('./bower.json').appPath || 'client/test',
    dist: 'dist',
    api: {
	development: 'http://localhost:3000/api/',
        production: '/api/'
    },
    site: {
        development: 'http://localhost:3000',
        production: ''
    },
	host: 'localhost'
  };

I then saved the file. I made no other edits to any other files.

In the project directory, I ran the "grunt serve" in a command window. A Chrome tab popped and, as expected, rerouted me to the login page: http://localhost:9000/#/login, which is currently blank.

Again, thank-you for helping me troubleshoot this.

**Comment by do4** [comment]
+1: Just did a clean install no modifications and get the same error. Master branch, latest commit 9923cdc. OS/X 10.10, Chrome 50, Node 4.4.4.

```
angular-scenario.js:20898 TypeError: Cannot read property 'then' of undefined
    at Object.enter (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3916:50)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4022:22
    at publicLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16210:29)
    at updateView (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4021:23)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3962:9
    at invokeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:17473:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16983:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16332:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16978:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16332:13) <!-- uiView:  -->(anonymous function) @ angular-scenario.js:20898
angular-scenario.js:20898 TypeError: Cannot read property 'then' of undefined
    at Object.enter (angular-ui-router.js:3916)
    at angular-ui-router.js:4022
    at publicLinkFn (angular-scenario.js:16210)
    at updateView (angular-ui-router.js:4021)
    at angular-ui-router.js:3959
    at Scope.$broadcast (angular-scenario.js:24081)
    at $state.transition.resolved.then.$state.transition (angular-ui-router.js:3352)
    at processQueue (angular-scenario.js:22510)
    at angular-scenario.js:22526
    at Scope.$eval (angular-scenario.js:23762)
```

Clean install of the `develop` branch, latest commit 3303664, doesn't have this issue.

**Comment by yieme** [comment]
+1: Just did a clean install no modifications and get the same error. Master branch 9923cdc. OS/X 10.10, Chrome 50, Node 4.4.4.

```
angular-scenario.js:20898 TypeError: Cannot read property 'then' of undefined
    at Object.enter (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3916:50)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4022:22
    at publicLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16210:29)
    at updateView (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4021:23)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3962:9
    at invokeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:17473:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16983:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16332:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16978:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular-scenario/angular-scenario.js:16332:13) <!-- uiView:  -->(anonymous function) @ angular-scenario.js:20898
angular-scenario.js:20898 TypeError: Cannot read property 'then' of undefined
    at Object.enter (angular-ui-router.js:3916)
    at angular-ui-router.js:4022
    at publicLinkFn (angular-scenario.js:16210)
    at updateView (angular-ui-router.js:4021)
    at angular-ui-router.js:3959
    at Scope.$broadcast (angular-scenario.js:24081)
    at $state.transition.resolved.then.$state.transition (angular-ui-router.js:3352)
    at processQueue (angular-scenario.js:22510)
    at angular-scenario.js:22526
    at Scope.$eval (angular-scenario.js:23762)
```

Did a clean install of the development branch and it doesn't have this issue.

**Comment by yieme** [comment]
Noticed version of node in package.json is 5.5.0 so upgraded. Problem persists.

**Comment by beeman** [comment]
It looks like it had something to do with the versions of the dependencies that `bower install` asks for:

```
Unable to find a suitable version for angular-animate, please choose one:
    1) angular-animate#~1.2.20 which resolved to 1.2.29 and is required by angular-toasty#0.1.8
    2) angular-animate#1.5.2 which resolved to 1.5.2 and is required by loopbackPrefix the choice with ! to persist it to bower.json

? Answer:: 2!
bower angular-animate                                resolution Saved angular-animate#1.5.2 as resolution

Unable to find a suitable version for angular-translate, please choose one:
    1) angular-translate#~2.6.0 which resolved to 2.6.1 and is required by angular-translate-loader-static-files#2.6.0, angular-translate-loader-url#2.6.0
    2) angular-translate#2.11.0 which resolved to 2.11.0 and is required by loopback
    3) angular-translate#>= 2.4.0 which resolved to 2.11.0 and is required by angular-schema-form-ui-select#0.1.1Prefix the choice with ! to persist it to bower.json

? Answer:: 2!
```

I've just updated master to pin these versions. Can you please try if this fixes the issue @Necter and @yieme?

**Comment by Necter** [comment]
Yes, it fixes the issue. It come up and I am able to login as the admin. Thank-you very much for your help!

**Comment by beeman** [comment]
Awesome @Necter! Good luck with the project!
