### ISSUE TITLE
Error while installing on Ubuntu

### ISSUE THREAD

**Issue by denzelwamburu** [beeman/loopback-angular-admin#49]
Hey,
Thanks for the great work i am looking to integrate the project to my site but while installing it renders the error below

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at Server._listen2 (/home/wamburu/Documents/loopback-angular-admin/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:71:23)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:486:13)
    at process.<anonymous> (/home/wamburu/Documents/loopback-angular-admin/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)

**Comment by macbroadcast** [comment]
hi @denzelwamburu , it means the address you are trying to bind the server to is in use.
Close the program using that port. 
Run:
ps -ax | grep node
You'll get something like:
60778 ??         0:00.62 /usr/local/bin/node abc.js
Then do:
kill -9 60778

hope this helps

**Comment by denzelwamburu** [comment]
@macbroadcast Thanks i got  7590 and  8952, but i killed them and managed to install it.
The route /explorer is working well but localhost:3000 returns errors from express i don't know what am missing.
404 Error: Cannot GET /

       at raiseUrlNotFoundError (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/server/middleware/url-not-found.js:15:17)
       at Layer.handle [as handle_request] (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
       at trim_prefix (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:302:13)
       at /home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:270:7
       at Function.proto.process_params (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:321:12)
       at next (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:261:10)
       at SendStream.error (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/node_modules/serve-static/index.js:107:7)
       at SendStream.emit (events.js:95:17)
       at SendStream.error (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/node_modules/send/index.js:244:17)
       at SendStream.onStatError (/home/wamburu/Documents/panel/loopback-angular-admin/node_modules/loopback/node_modules/express/node_modules/send/index.js:340:48)

**Comment by beeman** [comment]
@denzelwamburu did you do a grunt build?

**Comment by macbroadcast** [comment]
hi @denzelwamburu and @beeman I can reproduce the error on ubuntu : 

` > loopback-angular-admin@0.1.1 start /home/macbroadcast/development/loopback-angular-admin
> node server/server.js

Creating roles and users
Creating categories and products
Configuring passport
Running app in development mode
Creating default settings
Browse your REST API at http://localhost:3000/explorer
Web server listening at: http://localhost:3000/
Error: Cannot GET /
    at raiseUrlNotFoundError (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request] (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:302:13)
    at /home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:321:12)
    at next (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/lib/router/index.js:261:10)
    at SendStream.error (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/node_modules/serve-static/index.js:107:7)
    at SendStream.emit (events.js:95:17)
    at SendStream.error (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/node_modules/send/index.js:244:17)
    at SendStream.onStatError (/home/macbroadcast/development/loopback-angular-admin/node_modules/loopback/node_modules/express/node_modules/send/index.js:340:48)`

it seems a @strongloop related issue ? https://github.com/strongloop/loopback/pull/925

**Comment by beeman** [comment]
Could you please do a clean install of the current master to see it that fixes this issue?

    $ git clone git@github.com:beeman/loopback-angular-admin.git
    $ cd loopback-angular-admin
    $ npm install
    $ grunt build
    $ npm start

The project should now run on http://localhost:3000/.

I'm not sure why the `grunt build` step is still required, as it is defined in the `package.json`'s postinstall so it runs after `npm install`. Any clues on this are welcome :)

**Comment by denzelwamburu** [comment]
Hi @beeman i have tried the new one.Grunt builds without errors but the home page is blank.Appending a url like /auth/settings returns an error.

**Comment by beeman** [comment]
Please reopen if it's still the same with the latest master :)

**Comment by suhelrose** [comment]
Help: Why do this happen ?

Configuring passport
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at : http://0.0.0.0:3000/
Error: Cannot GET /dist/js/angular-strap.min.js.map
    at raiseUrlNotFoundError (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request] (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:317:13)
    at /home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:335:12)
    at next (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/suhela/Documents/turf/turf-assistant-web/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:180:13)
    at SendStream.emit (domain.js:422:20)
    at SendStream.error (/home/suhela/Documents/turf/turf-assistant-web/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/home/suhela/Documents/turf/turf-assistant-web/node_modules/send/index.js:433:12)
    at onstat (/home/suhela/Documents/turf/turf-assistant-web/node_modules/send/index.js:734:26)
    at /home/suhela/Documents/turf/turf-assistant-web/node_modules/async-listener/glue.js:188:31
    at FSReqWrap.oncomplete (fs.js:170:21)
Error: Cannot GET /dist/js/angular-spinner.js.map
    at raiseUrlNotFoundError (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request] (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:317:13)
    at /home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:335:12)
    at next (/home/suhela/Documents/turf/turf-assistant-web/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/suhela/Documents/turf/turf-assistant-web/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:180:13)
    at SendStream.emit (domain.js:422:20)
    at SendStream.error (/home/suhela/Documents/turf/turf-assistant-web/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/home/suhela/Documents/turf/turf-assistant-web/node_modules/send/index.js:433:12)
    at onstat (/home/suhela/Documents/turf/turf-assistant-web/node_modules/send/index.js:734:26)
    at /home/suhela/Documents/turf/turf-assistant-web/node_modules/async-listener/glue.js:188:31
    at FSReqWrap.oncomplete (fs.js:170:21)
/home/suhela/Documents/turf/turf-assistant-web/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'id' of undefined
    at /home/suhela/Documents/turf/turf-assistant-web/common/models/worker.js:84:25
    at notifySingleObserver (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:98:22)
    at iterate (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:181:13)
    at Object.async.eachSeries (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:197:9)
    at doNotify (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:95:11)
    at doNotify (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at doNotify (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at doNotify (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at Function.ObserverMixin._notifyBaseObservers (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
    at Function.ObserverMixin.notifyObserversOf (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
    at Function.ObserverMixin.notifyObserversOf (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
    at Function.ObserverMixin.notifyObserversOf (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
    at Function.ObserverMixin.notifyObserversOf (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
    at updateCallback (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-datasource-juggler/lib/dao.js:2103:13)
    at /home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-connector-mysql/lib/mysql.js:659:11
    at releaseConnectionAndCallback (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-connector-mysql/lib/mysql.js:149:17)
    at Query.<anonymous> (/home/suhela/Documents/turf/turf-assistant-web/node_modules/loopback-connector-mysql/lib/mysql.js:163:7)
    at Query.<anonymous> (/home/suhela/Documents/turf/turf-assistant-web/node_modules/continuation-local-storage/context.js:84:17)
    at bound (domain.js:376:14)
